# Generated by Django 5.2.4 on 2025-09-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
    ]
