# Generated by Django 4.2.2 on 2025-09-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
