# Generated by Django 5.2.4 on 2025-08-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_header_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="number_of_views",
            field=models.IntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
