# Generated by Django 5.2.4 on 2025-08-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование товара', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, help_text='Загрузите изображение товара', null=True, upload_to='catalog/photo/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену', max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Введите дату изменения', verbose_name='Дата изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
