# Generated by Django 4.2.2 on 2025-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publicated",
            field=models.BooleanField(
                default=False,
                help_text="Укажите признак публикации",
                verbose_name="Опубликовано",
            ),
        ),
    ]
